g2c1: Retrieve MAC address from OCOTP
Select CONFIG_MX28_FEC_MAC_IN_OCOTP so that we can get the MAC
address and avoid the following error:

U-Boot 2015.10-25149-gc7bc9c3 (Nov 18 2015 - 12:08:17 -0200)
...
Net:   FEC0 [PRIME]
Error: FEC0 address not set.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>